services:
  huntarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: huntarr
    volumes:
      - huntarr-config:/config
    environment:
      - TZ=America/New_York
    ports:
      - "9705:9705"
    restart: unless-stopped

volumes:
  huntarr-config:
    name: huntarr-config