services:
  huntarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: huntarr
    ports:
      - "9705:9705"
    volumes:
      - /config:/config
    environment:
      - TZ=America/New_York
    restart: unless-stopped
