name: Build Windows Installer

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
  workflow_dispatch: # Allows manual triggering

jobs:
  build-installer:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=Huntarr --icon=assets/huntarr.ico main.py
    
    - name: Install NSIS
      run: |
        choco install nsis -y
    
    - name: Build installer
      run: |
        makensis installer/huntarr-installer.nsi
    
    - name: Upload installer artifact
      uses: actions/upload-artifact@v3
      with:
        name: Huntarr-Setup
        path: installer/Huntarr-Setup.exe
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: installer/Huntarr-Setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}